name: riddleworld
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.2.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  fluttertoast: null
  cupertino_icons: ^1.0.2
  flutter_svg: ^2.0.10+1
  provider: ^6.1.2
  shared_preferences: ^2.2.3
  google_fonts: ^6.2.1
  url_launcher: ^6.3.0
  image_picker:
  just_audio:
  animated_widgets:
  flutter_staggered_animations: ^1.1.1
  assets_audio_player: ^3.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/icons/things_icon.svg
    - assets/icons/games_icon.svg
    - assets/icons/music_icon.svg
    - assets/icons/words_icon.svg
    - assets/icons/puzzle_icon.svg
    - assets/icons/math_icon.svg
    - assets/audios/
  fonts:
    - family: GoogleSans
      fonts:
        - asset: assets/fonts/GoogleSansRegular.ttf

